Core database models and migrations
pythonkumasi/Peer-Review pull request #20
Opened 2024-11-19 20:27 UTC by Frederick-Teye

Created the following:
1. Custom User model with student/lecturer roles
2.  Course model
3. Review model
4. Grade model for lecturer assessments
5. Set up model relationships and foreign keys
6. Implement model validation rules
7. Add database constraints for mutual reviews
8. Create migrations

2024-11-19 20:43 UTC, Frederick-Teye commented on accounts/admin.py
Okay bro, thank you...

2024-11-20 07:24 UTC, Frederick-Teye commented
I have pushed the new changes.

2024-11-20 07:54 UTC, JohananOppongAmoateng requested changes

2024-11-20 07:54 UTC, JohananOppongAmoateng commented on .vscode/settings.json
Put this file in a gitignore file

2024-11-20 07:54 UTC, JohananOppongAmoateng commented on peer_review/settings.py
U still haven't put the secret key as an env variable

2024-11-20 09:26 UTC, Frederick-Teye commented
Everything is done now, please check and give me feedback

2024-11-20 09:29 UTC, Frederick-Teye commented
I'm seeing some red reds over here about some checks were not successful

2024-11-22 09:51 UTC, merged